language: r
sudo: false
cache: packages
dist: trusty

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      # env: R_CODECOV=true
    - os: linux
      r: devel
    - os: osx
      osx_image: xcode7.3
      r: oldrel

# r_github_packages:
#   - jimhester/covr

# after_success:
#   - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

env:
   global:
     - R_BUILD_ARGS="--no-manual --no-build-vignettes"
     - R_CHECK_ARGS="--as-cran --no-manual --no-build-vignettes"

notifications:
 email:
   on_success: change
   on_failure: change
